version: '2'
services:
    team7-mysql:
        container_name: team7-mysql
        image: mysql:5.7.13
        # volumes:
        #     - ~/volumes/jhipster/team7/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=team7
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl
