version: '2'
services:
    team7-app:
        image: team7
        external_links:
            - team7-mysql:mysql
            - team7-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/team7?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    team7-mysql:
        extends:
            file: mysql.yml
            service: team7-mysql
    team7-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: team7-elasticsearch
